tails server vets writes

diff --git a/docker/manage b/docker/manage
--- a/docker/manage
+++ b/docker/manage
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-# Copyright 2017-2018 Government of Canada - Public Services and Procurement Canada - buyandsell.gc.ca
+# Copyright 2017-2019 Government of Canada - Public Services and Procurement Canada - buyandsell.gc.ca
 # 
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -43,7 +43,7 @@ usage() {
     rm -    Remove any existing application container, as built through this 
             script via docker-compose -- any further containers will remain.
 
-    tidy -  Remove all dangling (intermediate) images
+    tidy -  Remove all dangling images
 
 EOF
 exit 1
@@ -105,9 +105,55 @@ get_dc_args() {
     echo ${OPTS} ${DC_COMMAND} ${ARGS}
 }
 
+_update() {
+    PATH_SRC=$1
+    PATH_DEST=$2
+
+    RV=0
+    if [[ ! -f "${PATH_DEST}" || "${PATH_SRC}" -nt "${PATH_DEST}" ]]
+    then
+        if [ -f "${PATH_SRC}" ]
+        then
+            RV=1
+            cp -p "${PATH_SRC}" "${PATH_DEST}"
+        else
+            echo "Error: missing '${PATH_SRC}'; install von_base before von_conx" > /dev/stderr
+            exit 1
+        fi
+    fi
+
+    echo ${RV}
+}
+
 build() {
+    VON_BASE_FILES=$(dirname $(dirname "${SCRIPT_HOME}"))/von_base/files
+    RM_LIBINDY=$(_update "${VON_BASE_FILES}/libindy.so.tgz" "${SCRIPT_HOME}/libindy.so.tgz")
+    RM_INDY_POOL_DF=0
+
+    IMAGES=$(printf " %s" "${@}")
+    IMAGES=${IMAGES##*build}
+    if [[ -z "${IMAGES// /}" || "${IMAGES}" = *"indy_pool"* ]]
+    then
+        RM_INDY_POOL_DF=$(_update "${VON_BASE_FILES}/indy-pool.dockerfile" "${SCRIPT_HOME}/indy-pool.dockerfile")
+    fi
+
     echo -e "\nBuilding containers ..."
     docker-compose $@
+
+    # only remove files this process actually copied over - retain operator-overridden selections
+    if [ "${RM_LIBINDY}" -ne "0" ]
+    then
+        rm -rf "${SCRIPT_HOME}/libindy.so.tgz"
+    else
+        echo "Retaining '${SCRIPT_HOME}/libindy.so.tgz'"
+    fi
+
+    if [ "${RM_INDY_POOL_DF}" -ne "0" ]
+    then
+        rm -rf "${SCRIPT_HOME}/indy-pool.dockerfile"
+    else
+        echo "Retaining '${SCRIPT_HOME}/indy-pool.dockerfile"
+    fi
 }
 
 # --------------------------------------------------------------------------------------------------------------
